// This file is generated by `payload generate:importmap`.
// Run `npm run payload -- generate:importmap` to regenerate it whenever
// you add custom components to Payload.
export const importMap = {};
